### ISSUE TITLE
Hangs with explicitly represented zero-valued features

### ISSUE THREAD

**Issue by chrisc36** [allenai/ml#13]
If a zero valued feature is added to the one of the sparse feature maps the training will hang because the iterator in "CRFIndexedExample.java" in `flattenPredicates` will never get advanced.

**Comment by aria42** [comment]
Thanks. Can you work around this for the moment? I think we need to ignore zero valued features upstream since they can't contribute to anything and they make some optimizations impossible 






On Mon, Jul 27, 2015 at 11:10 AM -0700, "Christopher Clark" <notifications@github.com> wrote:












If a zero valued feature is added to the one of the sparse feature maps the training will hang because the iterator in "CRFIndexedExample.java" in flattenPredicates will never get advanced.

**Comment by chrisc36** [comment]
Sure, working around it will be no problem

**Comment by aria42** [comment]
Marking as resolved.
